version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: driver_monitoring
      POSTGRES_USER: dms_user
      POSTGRES_PASSWORD: dms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dms_user -d driver_monitoring"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=driver_monitoring
      - DB_USER=dms_user
      - DB_PASSWORD=dms_password
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  web-dashboard:
    build:
      context: ./web-dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    volumes:
      - ./web-dashboard:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  default:
    name: driver-monitoring-network